services:
  db:
    image: mysql:9.1.0
    restart: always
    environment:
      MYSQL_DATABASE: 'carsDB'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'yuji'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'yuji'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'S3cret'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./carsDB:/var/lib/mysql
      #      - ./src/main/resources/sql:/docker-entrypoint-initdb.d
      - ./db/data.sql:/docker-entrypoint-initdb.d/init.sql
  # Names our volume
volumes:
  my-db:
